name: ci

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: linux
            runner: ubuntu-latest
    env:
      TZ: UTC
      CGO_ENABLED: "1"
      GOTOOLCHAIN: local # avoid auto-upgrading the toolchain
      # Stabilise tests that rely on randomness/time
      GOFLAGS: -mod=readonly

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: false
          fetch-depth: 0
      - uses: actions/setup-go@v6
        with:
          go-version: "1.26.0"
          check-latest: false
          cache-dependency-path: "**/*.sum"
      - run: go version
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Vendoring and Tidy
        run: go mod tidy && go mod vendor
      - name: Install dependencies
        run: |
          go mod download
      - name: Run tests
        shell: bash
        run: |
          go test -mod=vendor -p 1 -timeout 0 -v -coverprofile=coverage.out -covermode=atomic -coverpkg=./... `go list -mod=vendor ./... | grep -v -E "(hasher|internal/bufpool|pkg/flog|pkg/neterrors|pkg/service_discovery)"`
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          flags: ${{ matrix.os }}
          name: coverage-${{ matrix.os }}
          fail_ci_if_error: false
          verbose: true
